#!/usr/bin/env python3
"""Generate human-readable rule views from the project Harness rule source."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

_SCRIPT_ROOT = Path(__file__).resolve().parent
if str(_SCRIPT_ROOT) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_ROOT))

from harness_runtime.core import atomic_write_text


RULE_ID = re.compile(r"^[A-Z][A-Z0-9]*-[0-9]{2,}$")
STAGE_ID = re.compile(r"^[a-z][a-z0-9-]{0,63}$")
SEVERITIES = {"critical", "standard"}


def load_rules(path: Path) -> dict:
    # JSON is a strict, dependency-free subset of YAML 1.2. The .yaml file remains the
    # single machine source while project Harnesses avoid a PyYAML runtime dependency.
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"invalid rule source {path}: {exc}") from exc
    if value.get("schema_version") != "1.0" or not isinstance(value.get("rules"), list):
        raise ValueError("rule source must contain schema_version=1.0 and a rules array")
    seen: set[str] = set()
    for rule in value["rules"]:
        rule_id = rule.get("id")
        if not isinstance(rule_id, str) or not RULE_ID.fullmatch(rule_id):
            raise ValueError(f"invalid rule id: {rule_id!r}")
        if rule_id in seen:
            raise ValueError(f"duplicate rule id: {rule_id}")
        seen.add(rule_id)
        if rule.get("severity") not in SEVERITIES:
            raise ValueError(f"invalid severity for {rule_id}")
        if not isinstance(rule.get("stages"), list) or not rule["stages"]:
            raise ValueError(f"{rule_id} must declare at least one stage")
        for stage in rule["stages"]:
            if not isinstance(stage, str) or (stage != "all" and not STAGE_ID.fullmatch(stage)):
                raise ValueError(f"invalid stage id for {rule_id}: {stage!r}")
        for field in ("title", "rule", "on_violation"):
            if not isinstance(rule.get(field), str) or not rule[field].strip():
                raise ValueError(f"{rule_id} is missing {field}")
    return value


def render_rules(title: str, rules: list[dict], source: str) -> str:
    lines = [
        f"# {title}",
        "",
        f"> Generated from `{source}`. Do not edit this file directly.",
        "",
    ]
    if not rules:
        lines.extend(["No additional rules apply to this stage.", ""])
        return "\n".join(lines)
    for rule in rules:
        lines.extend(
            [
                f"## {rule['id']}: {rule['title']}",
                "",
                rule["rule"],
                "",
                f"**On violation:** {rule['on_violation']}",
                "",
            ]
        )
    return "\n".join(lines)


def generate(source: Path, output_root: Path) -> dict:
    value = load_rules(source)
    rules = sorted(value["rules"], key=lambda item: item["id"])
    source_label = source.name
    critical = [rule for rule in rules if rule["severity"] == "critical"]
    atomic_write_text(
        output_root / "critical.md",
        render_rules("Critical Harness Rules", critical, source_label),
    )
    stage_names = sorted(
        {
            stage
            for rule in rules
            for stage in rule["stages"]
            if stage != "all"
        }
    )
    by_stage = output_root / "by-stage"
    if by_stage.is_symlink():
        raise ValueError(f"rule output by-stage directory must not be a symlink: {by_stage}")
    by_stage.mkdir(parents=True, exist_ok=True)
    expected = {f"{stage}.md" for stage in stage_names}
    for existing in by_stage.glob("*.md"):
        if existing.name not in expected:
            existing.unlink()
    for stage in stage_names:
        selected = [
            rule
            for rule in rules
            if rule["severity"] != "critical"
            and (stage in rule["stages"] or "all" in rule["stages"])
        ]
        atomic_write_text(
            by_stage / f"{stage}.md",
            render_rules(f"{stage.title()} Stage Rules", selected, source_label),
        )
    return {
        "rules": len(rules),
        "critical": len(critical),
        "stage_rules": sum(
            1 for rule in rules if rule["severity"] != "critical"
        ),
        "stages": stage_names,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output-root", type=Path, required=True)
    args = parser.parse_args()
    try:
        result = generate(args.source.resolve(), args.output_root.resolve())
    except ValueError as exc:
        print(json.dumps({"ok": False, "error": str(exc)}, indent=2))
        return 2
    print(json.dumps({"ok": True, **result}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
